GET http://localhost:3000/arrMusica
Accept: application/json

###

GET http://localhost:3000/playlists/4

###

POST http://localhost:3000/arrMusica HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:3000/arrMusica/4
Content-Type: application/json

###

DELETE http://localhost:3000/playlists/16

###